branches:
    only:
        - r0.0.1

language: go
 
go:
    - 1.9
    - tip
 
sudo: required
 
install:
    - go get -d github.com/emicklei/go-restful
    - go get -d github.com/emicklei/go-restful-openapi
    - go build github.com/waldoweng/beancask
 
script:
    - go test -timeout=30m github.com/waldoweng/beancask/storage -run ^$ -v -race -coverprofile=coverage.txt -covermode=atomic
    - go test -benchmem -run=^$ github.com/waldoweng/beancask/storage -bench ^$ -timeout=30m -v

after_success:
    - bash <(curl -s https://codecov.io/bash)
