branches:
    only:
        - r0.0.1

language: go
 
go:
    - 1.9
 
sudo: required
 
install:
    - go get -d github.com/emicklei/go-restful
    - go get -d github.com/emicklei/go-restful-openapi
    - go get -d github.com/common-nighthawk/go-figure
	- go get -d github.com/spf13/cobra
	- go get -d github.com/spf13/viper
    - go build github.com/waldoweng/beancask
 
script:
    - go test -timeout=30m github.com/waldoweng/beancask/storage -v -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)
